#!/usr/bin/env python3
"""Scan every REALIZABLE minimum-determinant FOUR-point Gram of Gamma_72.

Hermite's constant gamma_4 = 2^(1/2) is attained only by D_4, so a rank-4 sublattice of
Gamma_72 has det >= (8/2^(1/2))^4 = 1024 with equality exactly when it is a scaled D_4
(scripts/k4_gram_min_det.py checks this by brute force over all 339393 candidate Grams).  So
every determinant-1024 four-tuple spans the SAME lattice -- but the LP certificate is derived
from a numeric dual and is therefore basis-dependent, and the spread is worth having: moving
from one dual source to two already raised this dimension by 1 259 008.

Realizability is free.  The shipped four-tuple data/gamma72_d4_k4.npy generates a scaled D_4
whose 24 minimal vectors are all minimal vectors of Gamma_72, and all 104 determinant-1024
Grams occur among their four-tuples, so each is EXHIBITED rather than assumed.
"""
import itertools
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', '..', '..', 'common'))
from kpoint_lp import run3   # the one shared engine, ../../../../common/

HERE = os.path.dirname(os.path.abspath(__file__))
M1 = {0: 2603658750, 1: 1512243200, 2: 280928256, 3: 13959168, 4: 127800}
N = 6218175600
INCUMBENT = 359925453   # what a single dual source reached, before best-of-two
FLOOR = 331737984


def roots():
    """the 24 minimal vectors of the scaled D_4 generated by the shipped four-tuple"""
    G = np.load(os.path.join(HERE, '..', '..', 'dim73-95-gamma72-caps', 'data',
                             'gamma72_gram.npy')).astype(np.int64)
    U = np.load(os.path.join(HERE, '..', 'data', 'gamma72_d4_k4.npy')).astype(np.int64)
    D4 = np.array([[8, -4, -4, -4], [-4, 8, 0, 0], [-4, 0, 8, 0], [-4, 0, 0, 8]], dtype=np.int64)
    assert (U @ G @ U.T == D4).all()
    A = np.array([a for a in itertools.product(range(-2, 3), repeat=4) if any(a)],
                 dtype=np.int64)
    V = A @ U
    V = V[np.einsum('ij,jk,ik->i', V, G, V) == 8]
    assert len(V) == 24, len(V)
    return V, G


def main():
    lim = int(sys.argv[1]) if len(sys.argv) > 1 else 10 ** 9
    V, G = roots()
    IP = V @ G @ V.T
    seen = {}
    for t in itertools.permutations(range(24), 4):
        M = IP[np.ix_(t, t)]
        if int(round(np.linalg.det(M.astype(float)))) != 1024:
            continue
        seen.setdefault((int(M[0, 1]), int(M[0, 2]), int(M[0, 3]),
                         int(M[1, 2]), int(M[1, 3]), int(M[2, 3])), t)
    print(__doc__)
    print("realizable determinant-1024 four-point Grams: %d" % len(seen))
    print("the shipped D_4 pattern is one of them: %s" % ((-4, -4, -4, 0, 0, 0) in seen,))
    print()
    out = os.path.join(HERE, '..', 'data', 'scan_k4.json')
    done = {}
    if os.path.exists(out):
        done = {tuple(json.loads(k)): v for k, v in json.load(open(out)).items()}
        print("resuming: %d Grams already done" % len(done))
    best = None
    for i, (g, tri) in enumerate(sorted(seen.items())):
        if i >= lim:
            print("   ... stopping after %d Grams (pass a larger limit to continue)" % lim)
            break
        if g in done:
            v = done[g]
        else:
            t0 = time.time()
            a, b, c, d, e, f = g
            Gm = [[8, a, b, c], [a, 8, d, e], [b, d, 8, f], [c, e, f, 8]]
            r = run3(72, N, 8, [1, 2, 3, 4], M1, Gm, tdes=11)
            v = r[2] if r and r[0] == 'cert' else None
            done[g] = v
            json.dump({json.dumps(list(k)): x for k, x in done.items()}, open(out, 'w'))
            print("   %3d/%d  Gram %-26s certified %-12s %s  (%.0fs)"
                  % (i + 1, len(seen), str(g), v,
                     'BETTER' if v and v > INCUMBENT else '', time.time() - t0), flush=True)
        if v is not None and (best is None or v > best[0]):
            best = (v, g, tri)
    print()
    if best:
        v, g, tri = best
        print("best realizable four-point bound: %d   (incumbent %d, %+d)"
              % (v, INCUMBENT, v - INCUMBENT))
        print("   Gram %s, exhibited by sublattice roots %s" % (str(g), str(tri)))
        print("   factor %.2f over the floor %d" % (v / FLOOR, FLOOR))


if __name__ == '__main__':
    main()
