#!/usr/bin/env python3
"""Scan every REALIZABLE minimum-determinant three-point Gram of Gamma_72.

The k-point bound falls as det(Gram) rises, and for a rank-3 sublattice of Gamma_72 Hermite's
constant in dimension 3 (gamma_3 = 2^(1/3), attained only by A_3) forces

    8 <= min(L) <= gamma_3 * det(L)^(1/4 -> 1/3)   ==>   det(L) >= (8/2^(1/3))^3 = 256,

so det 256 is the best a triple can do, and every attaining triple spans a scaled A_3.

Realizability comes free.  The shipped four-tuple data/gamma72_d4_k4.npy generates a scaled D_4
sublattice of Gamma_72, whose 24 minimal vectors are all minimal vectors of Gamma_72; A_3 sits
inside D_4, so every Gram occurring among triples of those 24 is EXHIBITED, not conjectured.
This script enumerates them, runs the LP on each distinct det-256 Gram, and reports the best.
"""
import itertools
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', '..', '..', 'common'))
from kpoint_lp import run3   # the one shared engine, ../../../../common/

HERE = os.path.dirname(os.path.abspath(__file__))
M1 = {0: 2603658750, 1: 1512243200, 2: 280928256, 3: 13959168, 4: 127800}
N = 6218175600
INCUMBENT = 527597644


def sublattice_minimal_vectors():
    """the 24 minimal vectors of the scaled D_4 generated by the shipped four-tuple"""
    G = np.load(os.path.join(HERE, '..', '..', 'dim73-95-gamma72-caps', 'data',
                             'gamma72_gram.npy')).astype(np.int64)
    U = np.load(os.path.join(HERE, '..', 'data', 'gamma72_d4_k4.npy')).astype(np.int64)
    assert (U @ G @ U.T == np.array([[8, -4, -4, -4], [-4, 8, 0, 0],
                                     [-4, 0, 8, 0], [-4, 0, 0, 8]])).all()
    A = np.array([a for a in itertools.product(range(-2, 3), repeat=4) if any(a)],
                 dtype=np.int64)
    V = A @ U                                  # coefficient vectors in Gamma_72
    nrm = np.einsum('ij,jk,ik->i', V, G, V)
    V = V[nrm == 8]
    assert len(V) == 24, len(V)                # D_4 has exactly 24 roots
    return V, G


def main():
    V, G = sublattice_minimal_vectors()
    print(__doc__)
    print("minimal vectors of the exhibited sublattice: %d (D_4 has 24)" % len(V))
    IP = V @ G @ V.T
    seen = {}
    for i, j, k in itertools.permutations(range(len(V)), 3):
        a, b, c = int(IP[i, j]), int(IP[i, k]), int(IP[j, k])
        Gm = np.array([[8, a, b], [a, 8, c], [b, c, 8]], dtype=np.int64)
        d = int(round(np.linalg.det(Gm.astype(float))))
        if d != 256:
            continue
        seen.setdefault((a, b, c), (i, j, k))
    print("distinct realizable det-256 Grams among their triples: %d" % len(seen))
    # and that is ALL of them: enumerating every integer Gram with diagonal 8, off-diagonal in
    # [-4,4] (distinct minimal lines of Gamma_72 meet in at most 4), determinant 256 and
    # sublattice minimum 8 gives exactly the same 16, so this scan is exhaustive and the best
    # of it is the best the LP can certify at k = 3 for the optimal lattice, over all bases.
    co = np.array([v for v in itertools.product(range(-4, 5), repeat=3) if any(v)],
                  dtype=np.int64)
    every = []
    for a, b, c in itertools.product(range(-4, 5), repeat=3):
        Gm = np.array([[8, a, b], [a, 8, c], [b, c, 8]], dtype=np.int64)
        if int(round(np.linalg.det(Gm.astype(float)))) != 256:
            continue
        if np.linalg.eigvalsh(Gm.astype(float)).min() <= 1e-9:
            continue
        if np.einsum('ij,jk,ik->i', co, Gm, co).min() < 8:
            continue
        every.append((a, b, c))
    print("all det-256 Grams that exist at all: %d   exhaustive: %s"
          % (len(every), set(every) == set(seen)))
    assert set(every) == set(seen), (sorted(set(every) - set(seen)),
                                     sorted(set(seen) - set(every)))
    print()
    best = None
    for (a, b, c), tri in sorted(seen.items()):
        t0 = time.time()
        r = run3(72, N, 8, [1, 2, 3, 4], M1, [[8, a, b], [a, 8, c], [b, c, 8]], tdes=11)
        if not r or r[0] != 'cert':
            print("   %-14s no certificate" % str((a, b, c)))
            continue
        lp, v, m = r[1], r[2], r[3]
        flag = 'BETTER' if v > INCUMBENT else ''
        print("   Gram %-14s LP %.0f  certified %-11d  cells %-5d %s  (%.0fs)"
              % (str((a, b, c)), lp, v, m, flag, time.time() - t0), flush=True)
        if best is None or v > best[0]:
            best = (v, (a, b, c), tri, lp, m)
    print()
    v, g, tri, lp, m = best
    print("best realizable three-point bound: %d   (incumbent %d, gain %+d)"
          % (v, INCUMBENT, v - INCUMBENT))
    print("   Gram %s, exhibited by sublattice vectors %s" % (str(g), str(tri)))
    print("   LP optimum %.1f, so the integer certificate loses %.4f%%"
          % (lp, 100 * (lp - v) / lp))
    # No need to ship the triple: verify69.py rebuilds the 24 roots from the shipped four-tuple
    # and finds it deterministically, so there is nothing here that has to be stored.
    print("   verify69.py rebuilds this triple from data/gamma72_d4_k4.npy, so it is not shipped")


if __name__ == '__main__':
    main()
