"""What G_0 really is: the five 4-element blocks inside the kernel N.

G_0 = Cay(K_0, S_0) with K_0 = F_2^9, |S_0| = 20.  The five characters at eigenvalue -12 have
a common kernel N of dimension 5, and the quotient K_0/N = F_2^4 carries the Clebsch graph,
each s in S_0 mapping to one of its five generators v_1..v_5, four of S_0 per generator.

Splitting K_0 = N + (a linear section of the quotient) turns an independent set into sixteen
subsets Atil_c of N = F_2^5 with, for every Clebsch edge (c, c+v_i),

    Atil_c  n  ( Atil_{c+v_i} + Ghat_i )  =  empty,        Ghat_i in N, |Ghat_i| = 4.

Everything therefore depends on what the five 4-element sets Ghat_i look like inside F_2^5 --
whether they are affine planes, whether they share a direction space, and what they span.
That is what this prints.
"""
import sys, os, itertools, collections
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', '..', 'common'))
import numpy as np
from capcheck import golay

GOL = np.array(sorted(golay()), dtype=np.uint8)[:, 5:]
W = GOL.sum(1)
codes = [int("".join(map(str, r)), 2) for r in GOL]
Sraw = sorted(codes[i] for i in range(len(codes)) if 0 < W[i] <= 4)
even = [c for c in Sraw if bin(c).count('1') % 2 == 0]
sp, bas = {0}, []
for c in even:
    if c not in sp:
        bas.append(c); sp |= {x ^ c for x in sp}
D = len(bas); NV = 1 << D
idx = {}
for m in range(NV):
    v = 0
    for b in range(D):
        if m >> b & 1: v ^= bas[b]
    idx[v] = m
S0 = sorted(idx[c] for c in even)
print(__doc__)

chis = [c for c in range(NV)
        if sum(-1 if bin(c & s).count('1') & 1 else 1 for s in S0) == -12]
cls = lambda v: sum(((bin(v & c).count('1') & 1) << i) for i, c in enumerate(chis))
blocks = collections.defaultdict(list)
for s in S0:
    blocks[cls(s)].append(s)
print("blocks of S_0 by quotient class: %s" % {k: v for k, v in sorted(blocks.items())})
print("block sizes: %s" % sorted(len(v) for v in blocks.values()))

N = [v for v in range(NV) if cls(v) == 0]
print("|N| = %d" % len(N))
for k, blk in sorted(blocks.items()):
    diffs = sorted({a ^ b for a, b in itertools.combinations(blk, 2)})
    sub = {0}
    for d in diffs:
        sub |= {x ^ d for x in sub}
    print("  v=%2d block %s : pairwise differences %s -> they span a subgroup of size %d%s"
          % (k, blk, diffs, len(sub),
             "  (an AFFINE PLANE)" if len(sub) == 4 else ""))
    assert all(d in N for d in diffs), "differences must lie in N"

# do the five direction spaces coincide?
dirs = []
for k, blk in sorted(blocks.items()):
    sub = {0}
    for d in {a ^ b for a, b in itertools.combinations(blk, 2)}:
        sub |= {x ^ d for x in sub}
    dirs.append(frozenset(sub))
print("\ndistinct direction spaces among the five blocks: %d" % len(set(dirs)))
for d in sorted(set(dirs), key=sorted):
    print("   %s   used by %d blocks" % (sorted(d), sum(1 for x in dirs if x == d)))
joint = {0}
for d in dirs:
    for x in d:
        joint |= {y ^ x for y in joint}
print("subgroup generated by all five direction spaces: size %d (N has size %d)"
      % (len(joint), len(N)))
