#!/usr/bin/env python3
"""Generate paper/values.tex from RESULTS.md, so a bound appears in the manuscript ONCE.

    python mkvalues.py            # rewrite values.tex
    python mkvalues.py --check    # change nothing; exit 1 if it is out of date

WHY.  Every claimed bound used to be typed into kissing46.tex four times -- the introduction,
the theorem, the per-dimension table, and the count identity that derives it -- plus its gain in
two more tables.  Moving one dimension therefore meant six edits in five places, and the only
thing standing between that and a wrong number in print was factcheck.py noticing afterwards.
Now the manuscript says \\Kh{31} and the value is defined here, from RESULTS.md, which audit.py
generates from the packages.  Updating a bound is: re-run audit.py, re-run this, rebuild.

WHAT IS DEFINED, for every dimension RESULTS.md claims:

    \\Kh{31}     this work           238\\,662
    \\Kp{31}     previously published 238\\,350
    \\Kgain{31}  the difference      +312
    \\Kfac{31}   the ratio           1.00

The count identities in the text -- 175\\,904+61\\,968+118+672=\\Kh{31} -- keep their addends as
literals, because those are a derivation and not a bound; factcheck.py checks that they add up.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, os.pardir, 'RESULTS.md')
OUT = os.path.join(HERE, 'values.tex')


def tex_num(n):
    """123456 -> 123\\,456, the manuscript's thin-space grouping"""
    return format(int(n), ',').replace(',', r'\,')


def read_results():
    """{dim: (previously published, this work)} from the generated RESULTS.md table"""
    t = io.open(RESULTS, encoding='utf-8').read()
    out = {}
    for line in t.split('\n'):
        m = re.match(r'\|\s*(\d+)\s*\|\s*([\d\s  ]+)\|\s*\*\*([\d\s  ]+)\*\*', line)
        if m:
            num = lambda x: int(re.sub(r'[^0-9]', '', x))          # noqa: E731
            out[int(m.group(1))] = (num(m.group(2)), num(m.group(3)))
    return out


def render(vals):
    L = [r'% GENERATED by paper/mkvalues.py from ../RESULTS.md -- do not edit.',
         r'% Every claimed bound lives here once.  \Kh{n} this work, \Kp{n} previously',
         r'% published, \Kgain{n} the difference, \Kfac{n} the ratio.',
         r'\providecommand{\Kh}[1]{\csname KissHere#1\endcsname}',
         r'\providecommand{\Kp}[1]{\csname KissPrev#1\endcsname}',
         r'\providecommand{\Kgain}[1]{\csname KissGain#1\endcsname}',
         r'\providecommand{\Kfac}[1]{\csname KissFac#1\endcsname}',
         '']
    for d in sorted(vals):
        prev, here = vals[d]
        L.append(r'\expandafter\def\csname KissHere%d\endcsname{%s}' % (d, tex_num(here)))
        L.append(r'\expandafter\def\csname KissPrev%d\endcsname{%s}' % (d, tex_num(prev)))
        L.append(r'\expandafter\def\csname KissGain%d\endcsname{+%s}' % (d, tex_num(here - prev)))
        L.append(r'\expandafter\def\csname KissFac%d\endcsname{%.2f}' % (d, here / float(prev)))
    return '\n'.join(L) + '\n'


def main():
    vals = read_results()
    if not vals:
        print("mkvalues.py: RESULTS.md gave no rows -- has its table changed shape?")
        return 2
    text = render(vals)
    if '--check' in sys.argv:
        cur = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur == text:
            print("values.tex is up to date with RESULTS.md (%d dimensions)" % len(vals))
            return 0
        print("values.tex DISAGREES with RESULTS.md -- run: python paper/mkvalues.py")
        return 1
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(text)
    print("wrote values.tex: %d dimensions, %d macros" % (len(vals), 4 * len(vals)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
